import {
  INTRO_PRICE_LABEL,
  SINGLE_PHOTO_PRICE_LABEL,
  WEEKLY_CREDITS,
  WEEKLY_PRICE_LABEL,
} from "@loxa/shared";
import type { Metadata } from "next";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";

export const metadata: Metadata = { title: "Terms of use — Loxa" };

/** Required by App Store review, and linked from the app's profile screen. */
export default function Terms() {
  return (
    <>
      <SiteHeader />
      <main className="mx-auto max-w-5xl px-s6 pt-s6 pb-s10">
      <div className="max-w-2xl">
      <h1 className="mt-s5 font-serif text-4xl leading-tight">Terms of use</h1>
      <p className="mt-s2 font-mono text-[11px] text-[var(--ink-45)]">
        Last updated 27 August 2026
      </p>

      <div className="mt-s8 space-y-s5 text-[15px] leading-relaxed text-[var(--ink-72)]">
        <Section title="What Loxa does">
          Loxa shows you what a hair style and colour might look like on a photo
          of you. The images are generated by a model and are an illustration,
          not a promise: a real result depends on your hair, your stylist and
          things a photograph cannot know. Take one to a salon as a reference,
          not as a guarantee.
        </Section>

        <Section title="Credits">
          A credit is one generated photo. The weekly subscription includes{" "}
          {WEEKLY_CREDITS} photos each week. New subscribers pay{" "}
          {INTRO_PRICE_LABEL} for the first week, then {WEEKLY_PRICE_LABEL}{" "}
          until cancelled; the introductory price is offered once per Apple ID,
          so it does not apply if you have subscribed to Loxa before. Credits
          reset every Monday and do not carry over. If you run out you can buy a
          single photo for {SINGLE_PHOTO_PRICE_LABEL}. Credits are tied to the
          device the app is installed on; use Restore purchases if you reinstall
          or change phone.
        </Section>

        <Section title="Cancelling">
          Subscriptions renew until cancelled, and are managed in your Apple ID
          settings rather than in the app. Cancelling stops the next renewal; the
          week you have paid for runs to its end.
        </Section>

        <Section title="Your photos, your rights">
          You keep every right you have in the photos you upload and in the
          images Loxa generates from them. You confirm that you may use the photo
          you upload — in practice, that it is of you, or that whoever is in it
          agreed. Do not upload photos of other people without their permission.
        </Section>

        <Section title="Contact">
          <a href="mailto:hola@blankhexadecimal.com" className="underline underline-offset-4">
            hola@blankhexadecimal.com
          </a>
        </Section>
      </div>
      </div>
      </main>
      <SiteFooter />
    </>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="font-serif text-2xl text-ink">{title}</h2>
      <p className="mt-s2">{children}</p>
    </section>
  );
}
